project_id = "jqilueudbhgcgskvkvhe"

[functions.send-sms]
verify_jwt = true

[functions.register-device]
verify_jwt = true

[functions.verify-jwks]
verify_jwt = false

[functions.cleanup-old-data]
verify_jwt = false

[functions.admin-manage-users]
verify_jwt = true

[functions.manage-user-links]
verify_jwt = true
