export function extractProviderReference(payload, event) {
  const candidates = [
    payload?.provider_ref,
    payload?.providerReference,
    payload?.request_id,
    payload?.requestId,
    payload?.message_id,
    payload?.messageId,
    payload?.id,
    payload?.reference,
    payload?.reference_id,
    payload?.external_id,
    payload?.data?.provider_ref,
    payload?.data?.providerReference,
    payload?.data?.request_id,
    payload?.data?.requestId,
    payload?.data?.message_id,
    payload?.data?.messageId,
    payload?.data?.id,
    payload?.data?.reference,
    payload?.data?.reference_id,
    payload?.data?.external_id,
    payload?.result?.provider_ref,
    payload?.result?.providerReference,
    payload?.result?.request_id,
    payload?.result?.requestId,
    payload?.result?.message_id,
    payload?.result?.messageId,
    payload?.result?.id,
    payload?.result?.reference,
    payload?.result?.reference_id,
    payload?.result?.external_id,
    event?.provider_ref,
    event?.providerReference,
    event?.request_id,
    event?.requestId,
    event?.message_id,
    event?.messageId,
    event?.id,
    event?.reference,
    event?.reference_id,
    event?.external_id,
    event?.data?.provider_ref,
    event?.data?.providerReference,
    event?.data?.request_id,
    event?.data?.requestId,
    event?.data?.message_id,
    event?.data?.messageId,
    event?.data?.id,
    event?.data?.reference,
    event?.data?.reference_id,
    event?.data?.external_id,
    event?.result?.provider_ref,
    event?.result?.providerReference,
    event?.result?.request_id,
    event?.result?.requestId,
    event?.result?.message_id,
    event?.result?.messageId,
    event?.result?.id,
    event?.result?.reference,
    event?.result?.reference_id,
    event?.result?.external_id,
  ];

  for (const value of candidates) {
    if (typeof value === 'string' && value.trim()) {
      return value.trim();
    }
  }

  return null;
}
